import PropTypes from 'prop-types';

const propTypes = PropTypes.shape({
  allergen_classes: PropTypes.string,
  allergens: PropTypes.string,
  app_image_url: PropTypes.string,
  calories: PropTypes.string,
  category_id: PropTypes.number,
  category_name: PropTypes.string,
  delivery_days: PropTypes.string,
  description: PropTypes.string,
  display_options: PropTypes.number,
  end_date: PropTypes.string,
  end_date_str: PropTypes.string,
  height: PropTypes.string,
  id: PropTypes.number,
  increment: PropTypes.number,
  ingredients: PropTypes.string,
  kds_groups: PropTypes.array,
  large_image_url: PropTypes.string,
  length: PropTypes.string,
  max_quantity: PropTypes.number,
  menu_position: PropTypes.number,
  min_quantity: PropTypes.number,
  name: PropTypes.string,
  nutritional_info: PropTypes.object,
  option_groups: PropTypes.array,
  plu: PropTypes.string,
  price: PropTypes.string,
  sales_tax_override: PropTypes.string,
  service_restrictions: PropTypes.string,
  short_description: PropTypes.string,
  short_name: PropTypes.string,
  shorthand: PropTypes.string,
  sizes: PropTypes.array,
  slug: PropTypes.string,
  small_image_url: PropTypes.string,
  start_date: PropTypes.string,
  start_date_str: PropTypes.string,
  tag_classes: PropTypes.string,
  tags: PropTypes.string,
  taxes: PropTypes.array,
  temperature: PropTypes.string,
  use_options_wizard: PropTypes.number,
  weight: PropTypes.string,
  width: PropTypes.string
});

const defaultProps = {
  allergen_classes: '',
  allergens: '',
  app_image_url: null,
  calories: 'n/a',
  category_id: 1113,
  category_name: 'Entradas',
  delivery_days: null,
  description:
    'Corn from the cob, cotija cheese, homemade morita mayo and chili pequin',
  display_options: 0,
  end_date: null,
  end_date_str: '',
  height: null,
  id: 19708,
  increment: 1,
  ingredients: null,
  kds_groups: [],
  large_image_url:
    '//s3.amazonaws.com/betterboh/u/img/prod/51/1513812916_esquites_lg.jpg',
  length: null,
  max_quantity: 0,
  menu_position: 1,
  min_quantity: 1,
  name: 'Corn Esquites',
  nutritional_info: {},
  option_groups: [],
  plu: '',
  price: '3.95',
  sales_tax_override: null,
  service_restrictions: null,
  short_description: '',
  short_name: 'Corn Esquites',
  shorthand: '',
  sizes: [],
  slug: 'corn-esquites',
  small_image_url:
    '//s3.amazonaws.com/betterboh/u/img/prod/51/1513812916_esquites_sm.jpg',
  start_date: null,
  start_date_str: '',
  tag_classes: '',
  tags: '',
  taxes: [],
  temperature: 'Cold',
  use_options_wizard: 0,
  weight: null,
  width: null
};

export default {
  propTypes,
  defaultProps
};
