export default {
  PAYMENT_METHODS: 'PAYMENT_METHODS',
  EDIT_NAME: 'EDIT_NAME',
  EDIT_EMAIL: 'EDIT_EMAIL',
  EDIT_PHONE: 'EDIT_PHONE',
  EDIT_PASSWORD: 'EDIT_PASSWORD',
  EDIT_ALLERGENS: 'EDIT_ALLERGENS',
  EDIT_SERVICE_TYPE: 'EDIT_SERVICE_TYPE',
  EDIT_SERVICE_TYPE_TIME: 'EDIT_SERVICE_TYPE_TIME',
  MENU_NAVIGATION: 'MENU_NAVIGATION',
  MENU_FILTER: 'MENU_FILTER',
  ORDER_FEEDBACK_COMMENT: 'ORDER_FEEDBACK_COMMENT',
  EDIT_USER_ATTRIBUTE_REDIRECT: 'EDIT_USER_ATTRIBUTE_REDIRECT',
  CHANGE_LOCATION: 'CHANGE_LOCATION',
  CHANGE_DELIVERY_ADDRESS: 'CHANGE_DELIVERY_ADDRESS'
};
