export default {
  LINE_ITEM_EDITOR: 'LINE_ITEM_EDITOR',
  MENU_NAVIGATION: 'MENU_NAVIGATION',
  MENU_FILTER: 'MENU_FILTER',
  INVALID_ITEMS_IN_CART: 'INVALID_ITEMS_IN_CART',
  BELOW_DELIVERY_MINIMUM: 'BELOW_DELIVERY_MINIMUM',
  LOCATION_IS_CLOSED: 'LOCATION_IS_CLOSED',
  GENERIC_ERROR: 'GENERIC_ERROR'
};
